#2 Lesson#2
8pade8/HellOh pull request #1
Opened 2020-07-07 17:57 UTC by TatMik

2020-07-07 18:32 UTC, 8pade8 requested changes
в комментарии к коммиту пиши что сделал, а не номер урока

2020-07-07 18:32 UTC, 8pade8 commented on app/src/main/java/ru/trueproggers/helloh/MainActivity.kt
> +    private lateinit var mToolbar:Toolbar
отсутствует форматирование кода

2020-07-07 18:32 UTC, 8pade8 commented on app/src/main/java/ru/trueproggers/helloh/MainActivity.kt
> +    private fun createHeaser() {
некорректное имя метода

2020-07-09 14:08 UTC, 8pade8 approved these changes

2020-07-09 15:31 UTC, boJlek commented on app/src/main/java/ru/trueproggers/helloh/MainActivity.kt
> +                ProfileDrawerItem().withName("Mikhail Tatishchev")
Надеюсь себя правильно на английском записал..)

2020-07-09 15:31 UTC, boJlek commented on app/src/main/res/drawable/header.xml
> +</shape>
отформатировать

2020-07-09 15:31 UTC, boJlek commented on app/src/main/java/ru/trueproggers/helloh/MainActivity.kt
> +                    .withSelectable(false)
.withIdentifier(100) - на следующую строку

2020-07-09 15:37 UTC, boJlek requested changes
Исправить

2020-07-09 20:14 UTC, boJlek approved these changes

2020-07-10 11:39 UTC, 8pade8 approved these changes

2020-07-10 11:39 UTC, merged