#4 add UI Chats and Settings
8pade8/HellOh pull request #3
Opened 2020-07-14 15:31 UTC by cillywilly

no coments

2020-07-14 16:51 UTC, boJlek requested changes

2020-07-14 16:51 UTC, boJlek commented on app/src/main/java/ru/trueproggers/helloh/MainActivity.kt
> +            .replace(R.id.dataContainer, ChatsFragment()).commit()
Перенеси .commit() на следующую строчку

2020-07-14 16:51 UTC, boJlek commented on app/src/main/java/ru/trueproggers/helloh/MainActivity.kt
> +                    }
Перенеси .commit() на следующую строчку

2020-07-14 16:51 UTC, boJlek commented on app/src/main/res/layout/fragment_chats.xml
> +        android:text="@string/hello_blank_fragment" />
В уроке конечно было, но так-то TextView лишний, наверное)

2020-07-14 16:51 UTC, boJlek commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
тоже думаю лишнее

2020-07-14 16:53 UTC, 8pade8 requested changes

2020-07-14 16:53 UTC, 8pade8 commented on app/src/main/java/ru/trueproggers/helloh/ui/ChatsFragment.kt
> +import ru.trueproggers.helloh.R
лишний импорт

2020-07-14 16:53 UTC, 8pade8 commented on app/src/main/java/ru/trueproggers/helloh/ui/SettingsFragment.kt
> +import ru.trueproggers.helloh.R
лишний импорт

2020-07-14 16:53 UTC, 8pade8 commented on app/src/main/java/ru/trueproggers/helloh/ui/SettingsFragment.kt
> +import ru.trueproggers.helloh.databinding.FragmentChatsBinding
лишний импорт

2020-07-14 16:53 UTC, 8pade8 commented on app/src/main/res/layout/activity_main.xml
> -
верни назад пустую строку для удобства чтения

2020-07-15 06:36 UTC, boJlek commented on app/src/main/res/layout/fragment_chats.xml
> +        android:text="@string/hello_blank_fragment" />
Похоже не тот текствью убрал))

2020-07-15 06:37 UTC, boJlek requested changes
Вопрос

2020-07-15 15:52 UTC, 8pade8 commented on app/src/main/res/layout/fragment_chats.xml
> +        android:text="@string/hello_blank_fragment" />
Да, не тот, теперь тут еще и ссылка на несуществующий ресурс

2020-07-15 18:23 UTC, boJlek approved these changes

2020-07-15 19:14 UTC, merged