#5 some refactoring
8pade8/HellOh pull request #4
Opened 2020-07-16 17:42 UTC by 8pade8

2020-07-16 18:51 UTC, boJlek requested changes

2020-07-16 18:51 UTC, boJlek commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Оно нам нужно?))

2020-07-18 17:51 UTC, boJlek approved these changes

2020-07-20 13:34 UTC, TatMik approved these changes

2020-07-23 14:13 UTC, cillywilly reviewed
good

2020-07-23 19:22 UTC, merged