#9 refactoring
8pade8/HellOh pull request #8
Opened 2020-09-10 16:03 UTC by boJlek

2020-09-11 07:53 UTC, 8pade8 requested changes

2020-09-11 07:53 UTC, 8pade8 commented on app/src/main/java/ru/trueproggers/helloh/utilits/funs.kt
> +
удали лишние импорты

2020-09-11 07:53 UTC, 8pade8 commented on app/src/main/java/ru/trueproggers/helloh/utilits/funs.kt
> +fun AppCompatActivity.replacActivity(activity: AppCompatActivity) {
опечатка в названии функции

2020-09-11 07:53 UTC, 8pade8 commented on app/src/main/java/ru/trueproggers/helloh/ui/fragments/BaseFragment.kt
удали лишние импорты

2020-09-11 07:53 UTC, 8pade8 commented on app/src/main/java/ru/trueproggers/helloh/utilits/funs.kt
> +    fragmentManager?.beginTransaction()
не хватает this. перед fragmentManager

2020-09-11 07:53 UTC, 8pade8 commented on app/src/main/res/layout/activity_register.xml
это я не понял, что за изменения, издревле что-ли какие-то косяки были?

2020-10-04 09:17 UTC, boJlek commented on app/src/main/res/layout/activity_register.xml
ага, давние косяки)

2020-10-11 07:00 UTC, 8pade8 approved these changes

2020-10-11 07:00 UTC, merged